import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

shell = "/bin/zsh"

[window]
opacity = 0.5

[font]
normal = { family = "FiraCode", style = "Regular"}
